import:
    - '/ocr_tianchi/cfgs_20211110/det_db_base.yaml'
package: []
define:
  - name: 'Experiment'
    class: Experiment
    structure:
        class: Structure
        builder:
            class: Builder
            model: SegDetectorModel
            model_args:
                # backbone: deformable_resnet50
                backbone: resnet50
                decoder: SegDetector
                decoder_args:
                    adaptive: True
                    in_channels: [256, 512, 1024, 2048]
                    k: 50
                loss_class: L1BalanceCELoss

        representer:
            class: SegDetectorRepresenter
            max_candidates: 1000
        measurer:
            class: QuadMeasurer
        visualizer:
            class: SegDetectorVisualizer
    train:
        class: TrainSettings
        data_loader:
            class: DataLoader
            dataset: ^train_data
            # batch_size: 10
            batch_size: 16
            # batch_size: 24
            num_workers: 16
        checkpoint:
            class: Checkpoint
            start_epoch: 0
            start_iter: 0
            resume: null
        model_saver:
            class: ModelSaver
            dir_path: model
            # save_interval: 985
            # save_interval: 2046
            save_interval: 2558
            signal_path: save
        scheduler:
            class: OptimizerScheduler
            optimizer: "SGD"
            optimizer_args:
                lr: 0.007
                momentum: 0.9
                weight_decay: 0.0001
            learning_rate:
                class: DecayLearningRate
                epochs: 50
        # epochs: 0
        epochs: 20

    validation: &validate
        class: ValidationSettings
        data_loaders:
            icdar2015:
                class: DataLoader
                dataset: ^validate_data
                batch_size: 1
                num_workers: 8
                collect_fn:
                    class: ICDARCollectFN
        visualize: false
        # interval: 985
        # interval: 2046
        interval: 17050000
        exempt: 1

    logger:
        class: Logger
        verbose: true
        level: info
        # log_interval: 500
        # log_interval: 2046
        log_interval: 1705

    evaluation: *validate
