Global:
  use_gpu: False
  distributed: True
  # epoch_num: 1
  epoch_num: 16
  log_smooth_window: 20
  # print_batch_step: 10
  print_batch_step: 10
  save_model_dir: ./output/rec_chinese_common_train_v2.0_20211027
  save_epoch_step: 500
  # evaluation is run every 5000 iterations after the 4000th iteration
  # eval_batch_step: [0, 1395]
  # eval_batch_step: [0, 696]
  eval_batch_step: [0, 104400000]
  cal_metric_during_train: True
  pretrained_model:  /ocr_data/pretrain/ch_ppocr_server_v2.0_rec_pre/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: True
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_chinese_common_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    # name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /ocr_data/rec_data_20211027/crop_imgs_train/
    label_file_list:
      - /ocr_data/rec_data_20211027/crop_imgs_train/rec_gt_train_20211027.txt
      - /ocr_data/rec_data_20211110/crop_imgs_train/rec_gt_train_20211110.txt
    ratio_list: 1.0
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
          aug_prob: 0.4
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    # batch_size_per_card: 128
    batch_size_per_card: 8
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /ocr_data/rec_data_20211027/crop_imgs_val/
    label_file_list: ["/ocr_data/rec_data_20211027/crop_imgs_val/rec_gt_val_20211027.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    # batch_size_per_card: 128
    batch_size_per_card: 8
    num_workers: 8
